install.packages("caret", repos = 'https://lib.ugent.be/CRAN/')
install.packages("tidyr", repos = 'https://lib.ugent.be/CRAN/')
install.packages("ggthemes", repos = 'https://lib.ugent.be/CRAN/')
install.packages("MASS", repos = 'https://lib.ugent.be/CRAN/')
install.packages("e1071", repos = 'https://lib.ugent.be/CRAN/')
install.packages("randomForest", repos = 'https://lib.ugent.be/CRAN/')
install.packages("gbm", repos = 'https://lib.ugent.be/CRAN/')
install.packages("lda", repos = 'https://lib.ugent.be/CRAN/')

install.packages("ggthemes")
install.packages("MASS")
install.packages("e1071")
install.packages("randomForest")
install.packages('beanplot')
install.packages('C50')

library(dplyr)
library(caret)
library(tidyr)
library(ggthemes)
library(MASS)
library(e1071)
library(randomForest)
library(gbm)
library(lda)

library(beanplot)
library(C50)

